name: Build Yocto IPK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gawk wget git diffstat unzip texinfo \
          gcc build-essential chrpath socat cpio python3 python3-pip \
          python3-pexpect xz-utils debianutils iputils-ping python3-git \
          python3-jinja2 libgl1-mesa-dev libsdl1.2-dev xterm \
          python3-subunit mesa-common-dev zstd liblz4-tool file
      - name: Clone Poky kirkstone
        run: |
          git clone -b kirkstone https://github.com/yoctoproject/poky.git ~/poky
          git clone -b kirkstone https://github.com/agherzan/meta-raspberrypi ~/poky/meta-raspberrypi
          git clone -b kirkstone https://github.com/openembedded/meta-openembedded ~/poky/meta-openembedded

      - name: Copy meta layer
        run: |
          cp -r . ~/poky/meta-subbareddy

      - name: Setup build environment
        run: |
          cd ~/poky
          source oe-init-build-env build
          bitbake-layers add-layer ~/poky/meta-openembedded/meta-oe
          bitbake-layers add-layer ~/poky/meta-openembedded/meta-python
          bitbake-layers add-layer ~/poky/meta-openembedded/meta-networking
          bitbake-layers add-layer ~/poky/meta-openembedded/meta-multimedia
          bitbake-layers add-layer ~/poky/meta-raspberrypi
          bitbake-layers add-layer ~/poky/meta-subbareddy

      - name: Copy local.conf
        run: |
          cp ~/poky/meta-subbareddy/conf/local.conf ~/poky/build/conf/local.conf

      - name: Build calcapp
        run: |
          cd ~/poky
          source oe-init-build-env build
          bitbake calcapp

      - name: Build sysmonitor
        run: |
          cd ~/poky
          source oe-init-build-env build
          bitbake sysmonitor

      - name: Find IPK files
        run: |
          find ~/poky/build/tmp/deploy/ipk/cortexa72/ -name "*.ipk" \
          | grep -v dbg | grep -v dev

      - name: Upload IPKs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest OTA Release
          files: |
            ~/poky/build/tmp/deploy/ipk/cortexa72/calcapp_*.ipk
            ~/poky/build/tmp/deploy/ipk/cortexa72/sysmonitor_*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
